 <!-- Core JS -->
 <script src="{{ asset('assets-front') }}/js/jquery-3.3.1.min.js"></script>
 <script src="{{ asset('assets-front') }}/js/bootstrap.min.js"></script>
 <script src="{{ asset('assets-front') }}/js/jquery.nice-select.min.js"></script>
 <script src="{{ asset('assets-front') }}/js/jquery.nicescroll.min.js"></script>
 <script src="{{ asset('assets-front') }}/js/jquery.magnific-popup.min.js"></script>
 <script src="{{ asset('assets-front') }}/js/jquery.countdown.min.js"></script>
 <script src="{{ asset('assets-front') }}/js/jquery.slicknav.js"></script>
 <script src="{{ asset('assets-front') }}/js/mixitup.min.js"></script>
 <script src="{{ asset('assets-front') }}/js/owl.carousel.min.js"></script>
 <script src="{{ asset('assets-front') }}/js/main.js"></script>
